[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "pokedex/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["pokedex"]

[project]
name = "pokedex"
# readme = "README.md"
description = "To be written."
authors = [
    {name = "Felix Soubelet", email = "felix.soubelet@cern.ch"},
]
license = "MIT"
dynamic = ["version"]
requires-python = ">=3.9"

classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Utilities",
]

dependencies = [
    "requests >= 2.25",
    "loguru < 1.0",
    "pydantic >= 2.5",
    "pysimplegui >= 5.0",
]

[project.urls]
homepage = "https://github.com/fsoubelet/pokedex"
repository = "https://github.com/fsoubelet/pokedex"

[tool.ruff]
# Generate Python 3.9-compatible code.
target-version = "py39"
line-length = 110

[tool.ruff.lint]
ignore = ["B019"]
